services:
  - type: web
    name: aqui-perto-api
    runtime: python
    region: virginia
    plan: free
    rootDir: backend

    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    initialDeployHook: python manage.py loaddata initial_catalog

    healthCheckPath: /api/
    autoDeployTrigger: commit

    envVars:
      - key: DJANGO_DEBUG
        value: "0"

      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: aqui-perto-db
          property: connectionString

databases:
  - name: aqui-perto-db
    databaseName: aqui_perto
    user: aqui_perto
    region: virginia
    plan: free
